.TH alff 1

.SH NAME
alff \- A Linux Firewall Framework

.SH SYNOPSIS
.B alff generate

.B alff push 
.I [ machine_id ]

.B alff
.I function

.SH DESCRIPTION
.IR  alff

.SH NO WARRANTIES
This program is distributed in the hope that it  will  be  useful,  but
WITHOUT  ANY  WARRANTY;  without  even  the  implied  warranty  of MER-
ANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  General
Public License for more details.

.SH "SEE ALSO"
.BR alff.conf (5)

Homepage: http://alff.rfc2324.org

.SH AUTHOR
Maximilian Wilhelm <max@rfc2324.org>
