.TH alff 1

.SH NAME
alff \- A Linux Firewall Framework

.SH SYNOPSIS
.B alff generate

.B alff push 
.I [ machine_id ]

.B alff -list
\||\| 
.I function [ option ]

.SH DESCRIPTION
.B alff
is a command line tool which was designed to easily manage your iptables based firewall rules.
Alff does know about things like services, networks and firewall machines.

.SH NO WARRANTIES
This program is distributed in the hope that it  will  be  useful,  but
WITHOUT  ANY  WARRANTY;  without  even  the  implied  warranty  of MER-
ANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  General
Public License for more details.

.SH "SEE ALSO"
.BR alff.conf (5)

Homepage: http://alff.rfc2324.org

.SH AUTHOR
Maximilian Wilhelm <max@rfc2324.org>
