.TH alff-cat 1

.SH NAME
alff-cat \- A Linux Firewall Framework

.SH SYNOPSIS
alff-cat will be invoked by 
.B alff push

.SH DESCRIPTION
.B alff-cat
is the firewall side tool to load the generated rules by alff.

.SH NO WARRANTIES
This program is distributed in the hope that it  will  be  useful,  but
WITHOUT  ANY  WARRANTY;  without  even  the  implied  warranty  of MER-
ANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  General
Public License for more details.

.SH "SEE ALSO"
.BR alff.conf (5)

Homepage: http://alff.rfc2324.org

.SH AUTHOR
Maximilian Wilhelm <max@rfc2324.org>
