#!/usr/bin/perl -w
#
# alff getOption
#
# Get a specific option from the alff.conf file
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 28 Apr 2006 13:35:56 +0200
#

use strict;
use Alff::Config;

my $config_opt;
my $nocheck = 0;

foreach my $arg ( @ARGV ) {

	if ( $arg eq "-nocheck" ) {
		$nocheck = 1;
		next
	}

	$config_opt = $arg;
}

if ( ! $config_opt ) {
	print STDERR "Usage: alff getOption { security_classes , [option] }\n";
	exit 1;
}

# Load configuration
my $config = Alff::Config->new( nocheck => $nocheck  );
my $config_entry;

if ( $config_opt eq "security_classes" ) {
	$config_entry = join " ", $config->getSecurityClasses();
} else {
	$config_entry = $config->getOption( $config_opt );
}

if ( $config_entry ) {
	print "$config_entry\n";
} else {
	print STDERR "Error: No config entry for $config_opt\n";
	exit 1;
}
