#!/usr/bin/perl -w
#
# fwrbm getOption
#
# Get a specific option from the fwrbm.conf file
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 28 Apr 2006 13:35:56 +0200
#

use strict;
use Fwrbm::Config;

my $configfile = "/etc/fwrbm/fwrbm.conf";

my $config_opt;
my $nocheck = 0;

foreach my $arg ( @ARGV ) {

	if ( $arg eq "-nocheck" ) {
		$nocheck = 1;
		next
	}

	$config_opt = $arg;
}

if ( ! $config_opt ) {
	print STDERR "Usage: fwrbm getOption [option]\n";
	exit 1;
}

# Load configuration
my $config = Fwrbm::Config->new( configfile => $configfile, nocheck => $nocheck  );

my $config_entry = $config->getOption( $config_opt );

if ( $config_entry ) {
	print "$config_entry\n";
} else {
	print STDERR "Error: No config entry for $config_opt\n";
	exit 1;
}
