#!/bin/sh
#
# loadUserRules
#
# Maximilian Wilhelm <mwilhelm@math.uni-paderborn.de>
#  -- Fri, 23 Dec 2005 20:15:54 +0100
#

BASE_DIR="/firewall/current"
CONFIG_DIR="/etc/fwrbm"
RULES_D="${CONFIG_DIR}/rules.d"

if [ ! -d "${RULES_D}" ]; then
	echo "Error: rules.d ${RULES_D} does not exist."
	exit 1
fi

echo -n " * Loading user defined rules... "
for rules_file in `find "${RULES_D}" -type f ! -name \*_to_\* ! -name .\* ! -name \*default\* ! -name \*CVS\*`; do
	echo -n "."
	if ! sh "${rules_file}"; then
		echo "Warning: Error while loading user rule file ${rules_file}!" >&2
	fi
done
echo " done."
