#!/bin/sh
#
# removeService <servicename>
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Mon, 19 Dec 2005 14:01:30 +0100
#

set -e

if ! which bc >/dev/null 2>/dev/null; then
	echo "This programm needs 'bc' installed to work correctly. Exiting." >&2
	exit 1
fi

SERVICES_D="/etc/alff/services.d"


if [ -z "${1}" ]; then
	echo "Usage: $0 service" >&2
	exit 1
fi

SERVICE="${1}"
echo "alff: Removing service ${SERVICE}..."

##
# Check for service dir
if [ ! -d "${SERVICES_D}" ]; then
	echo "Error: services.d directory ${SERVICES_D} does not exists." >&2
	exit 1
fi

if [ !  -f "${SERVICES_D}/${SERVICE}" ]; then
	echo "Error: Configuration for service ${SERVICE} does not exists." >&2
	exit 1
fi

# Check if service is still referenced by firewall rules
echo -n " * Checking if service is still referenced... "

SRV_REF_COUNT=`iptables -L -n | grep -c "^allowSrv${SERVICE}" || /bin/true`

# Check for references in service chains
SERVICE_CHAINS=`echo $(iptables -L -n  | grep '^Chain allowServices' | cut -d' ' -f2)`
SERVICES_CHAINS_REF_COUNT="0"

for srv_chain in ${SERVICE_CHAINS}; do
	# || /bin/true to work around return code '1' of grep or let if the value would be 0
	let SERVICES_CHAINS_REF_COUNT=${SERVICES_CHAINS_REF_COUNT}+`iptables -n -L ${srv_chain} | grep -c "^allowSrv${SERVICE}" || /bin/true` || /bin/true
done

let SRV_REF_COUNT_MISC=${SRV_REF_COUNT}-${SERVICES_CHAINS_REF_COUNT} || /bin/true

if [ ${SRV_REF_COUNT} -gt 0 ]; then
	if [ ${SRV_REF_COUNT_MISC} -gt 0 ]; then
		echo "YES."
		echo "   Error: Service ${SERVICE} is still referenced by firewall rules." >&2
		echo "   You have to remove this rules before you can delete the service." >&2
		exit 1
	else
		export INTERNAL_REF="true"
		echo "YES."
		echo "   Attention: Service ${SERVICE} is still referenced by alff internal rules.">&2
		echo "   You have to run  'alff reload' to remove those references.">&2
	fi
else
	echo "no."
fi

##
# Let's go
CHAIN="allowSrv${SERVICE}"

# If chain exists, remove it
if iptables -L ${CHAIN} -n > /dev/null 2>/dev/null; then
	echo -n " * Flushing chain allowSrv${SERVICE}... "
	iptables -F ${CHAIN} && echo "done." || echo "FAILED!"

	if [ ! "${INTERNAL_REF}" ]; then
		echo -n " * Remove chain allowSrv${SERVICE}... "
		iptables -X ${CHAIN} && echo "done." || echo "FAILED!"
	fi
fi

echo -n " * Removing configuration for service ${SERVICE}... "
rm "${SERVICES_D}/${SERVICE}" && echo "done." || echo "FAILED!"
