#!/usr/bin/env sh
#
# accept_established_connections
#
# Accept ESTABLISHED and RELATED connections by looking at the 
# connection tracking table
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 20:40:49 +0200
#

# Nice litte trick to make this script more flexible
# The chain in which the spoofcheck chain should be hooked in has to be
# specified by providing _$CHAIN at the end of the symlink name to this
# script.
# (Thanks to the munin if_ plugin coders for this idea)
CHAIN=`basename $0 | awk -F_ '{ print $NF }'`

if ${CHAIN}; then
	echo -n " * Creating rule to ACCEPT established connections... "
	iptables -A ${CHAIN} -m state --state RELATED,ESTABLISHED -j ACCEPT && echo "done." || echo "FAILED!"
else
	echo "Error: You did not specify the chain in which 'spoofcheck' should be hooked in" >&2
fi

