#!/usr/bin/env sh
#
# create_chain_dont_log
#
# Create a chain for things we want to be silently discarded.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Wed, 12 Apr 2006 21:17:42 +0200
#

##
# If not already there, create ${chain} (avoid 'iptables -F')
if ! iptables -F dont_log >/dev/null 2>&1; then
	iptables -N dont_log
fi

# ft=sh
