#!/usr/bin/env sh
#
# 01drop_spoofed
#
# Drop spoofed connection attemps
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Wed, 12 Apr 2006 19:00:04 +0200

##
# Make sure we have (an empty) chain
if ! iptables -F spookcheck; then
	iptables -N spookcheck
fi

##
# RFC1918 networks
#
iptables -A spookcheck -p all -i eth+ -s 10.0.0.0/8 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 10.0.0.0/8 -j DROP
#
iptables -A spookcheck -p all -i eth+ -s 172.16.0.0/12 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 172.16.0.0/12 -j DROP
#
iptables -A spookcheck -p all -i eth+ -s 192.168.0.0/16 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 192.168.0.0/16 -j DROP

##
# RFC 3330 networks
#
# documentation network
iptables -A spookcheck -p all -i eth+ -s 192.0.2.0/24 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 192.0.2.0/24 -j DROP
# link local
iptables -A spookcheck -p all -i eth+ -s 169.254.0.0/16 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 169.254.0.0/16 -j DROP

##
# Loopback address on eth* is probably not right
iptables -A spookcheck -p all -i eth+ -s 127.0.0.0/8 -j LOG --log-prefix "fwrbm spoofed: "
iptables -A spookcheck -p all -i eth+ -s 127.0.0.0/8 -j DROP
