#!/bin/sh
#
# Execute an alff plugin and redirect fd3 to an outfile named like $1.
#
# This build-in routine will be called when 'alff generate'ing rules
# with the full path to the plugin which should be run as parameter.
#
# CACHE_DIR_BUILD and PLUGIN_D have to be exported before running this
# script, otherwise it will fail.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 09 Feb 2007 18:09:41 +0100
#

plugin_path="${1}"
plugin_name=`basename "${1}"`

function die() { # Nice little die function # {{{
	local msg="$@"
	echo " ERROR: alff generate: ${msg}" >&2
	# XXX This exitcode is required to tell xargs (which calls us) to stop processing of further plugins.
	exit 255
} #}}}

if [ ! "${1}" ]; then
	die "Called without arguments."
fi

# Check Environment # {{{
if [ ! "${CACHE_DIR_BUILD}" ]; then
	die "CACHE_DIR_BUILD is not set but required."
fi

if [ ! -d "${CACHE_DIR_BUILD}" ]; then
	die "CACHE_DIR_BUILD does not exist. This should not have happend."
fi

if [ ! "${PLUGIN_D}" ]; then
	die "PLUGIN_D is not set but required."
fi
# }}}

##
# Check for bad karma # {{{
if [ `dirname "${1}"` != "${PLUGIN_D}" ]; then
	die "I refuse to execute a plugin not from plugin.d"
fi

if [ ! -f "${plugin_path}" -a ! -L "${plugin_path}" ]; then
	die "Plugin with name \"${plugin_name}\" is neither a file nor a link. Are you sure this is OK?"
fi

if [ -L "${plugin_path}" ]; then
	plugin_absolute=`readlink -e "${plugin_path}"`
	if [ -z "${plugin_absolute}" ]; then	
		die "Plugin \"${plugin_name}\" is a dangling symlink."
	fi

	if [ ! -x ${plugin_absolute} ]; then
		die "Plugin \"${plugin_name}\" is a symlink to an unexecutable file."
	fi
fi
# }}}


if [ ! -x "${plugin_path}" ]; then
	case "${plugin_name}" in
		POLICY|README)
			exit 0
			;;
	
		*)
			echo " INFO: Plugin \"${plugin_name}\" is not executeable." >&2
	esac;
fi

##
# OK, now everything should be fine.
if ! sh -c "${plugin_path}" 3> "${CACHE_DIR_BUILD}/${plugin_name}"; then
	die "There occured errors while executing plugin \"${plugin_name}\"."
fi

# vim:foldmethod=marker
