#!/bin/bash -e
#
# loadUserRules
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 23 Dec 2005 20:15:54 +0100
#

. "/usr/share/alff/lib/function-routines"

RULES_D="${ALFF_CONFIG_DIR}/rules.d"

if [ ! -d "${RULES_D}" ]; then
	echo "Error: rules.d ${RULES_D} does not exist."
	exit 1
fi

echo -n " * Loading user defined rules... "
# Load all files *not* like *_to_*, default_to_*, *_to_default and everything starting with a '.'
for rules_file in `find "${RULES_D}" -type f ! -name \*_to_\* ! -name .\* ! -name \*default\* ! -name README`; do
	echo -n "."
	cat "${rules_file}" >&3
done
echo " done."
