#!/bin/bash
#
# show-function-info
#
# This build-in function from alff is used to generate an informative overview
# about the function available.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Sat, 25 Nov 2006 22:04:23 +0100
#

# Check for environment
if [ -z "${ALFF_FUNCTION_DIR}" ]; then
	echo "ERROR: ALFF_FUNCTION_DIR not set. Did you run $0 from within alff?!" >&2
	exit 1
fi

function_name="${1}"

if [ -z "${function_name}" ]; then
	echo "ERROR: Usage: $0 function_name" >&2
	exit 1
fi

# As this script is called with the full pathname of the function,
# we may have to strip the path...
if echo "${function_name}" | grep -q '/'; then
	function_name=`basename "${function_name}"`
fi

if [ ! -f "${ALFF_FUNCTION_DIR}/${function_name}" ]; then
	echo "ERROR: Alff function \"${function_name}\" does not exist." >&2
	exit 1
fi

function_desc=`grep '^# ALFF_FUNCTION_DESC' "${ALFF_FUNCTION_DIR}/${function_name}" | sed -e 's/# ALFF_FUNCTION_DESC[[:space:]]*//'`
if [ -z "${function_desc}" ]; then
	function_desc="No description available."
fi

echo " * ${function_name}	(${function_desc})"
