#!/usr/bin/perl -w
#
# acceptInterFirewallTraffic
#
# Maximilian Wilhelm <max@rfc2324.org
#  -- Fri, 03 Nov 2006 14:53:06 +0100
#

use strict;
use Alff::Config;
use Alff::Main;
use Net::CIDR;

my $alff = Alff::Main->new();
my $config = Alff::Config->new();

my @machine_IDs = $config->getMachineIDs();

if ( scalar ( @machine_IDs ) > 0 ) {
	foreach my $machine_id ( @machine_IDs ) {
		my $machine_ip = $config->getMachineIP( $machine_id );
		my $machine_ip6 = $config->getMachineIP6( $machine_id );
		if( $machine_ip ) {
	
			if ( ! Net::CIDR::cidrvalidate( $machine_ip ) ) {
				print STDERR "Error: Invalid IPv4 address for machine $machine_id.\n";
				exit 1;
			}
						
			$alff->write_line("iptables -A INPUT -s $machine_ip -j ACCEPT");
		}

		if( $machine_ip6 ) {
	
			if ( ! Net::CIDR::cidrvalidate( $machine_ip6 ) ) {
				print STDERR "Error: Invalid IPv6 address for machine $machine_id.\n";
				exit 1;
			}
						
			$alff->write_line("ip6tables -A INPUT -s $machine_ip6 -j ACCEPT");
		}

	}
} else {
	print STDERR "Attention: acceptInterFirewallTraffic: No machines found\n";
}
