#!/bin/sh -e 
#
# accept_established_connections_
#
# Accept ESTABLISHED and RELATED connections by looking at the 
# connection tracking table
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 20:40:49 +0200
#

. /usr/share/alff/lib/plugin-routines

CHAIN=`getOption $1`

if [ "${CHAIN}" ]; then
	echo " * Creating rule to ACCEPT established connections... "
	echo "iptables -A ${CHAIN} -m state --state RELATED,ESTABLISHED -j ACCEPT" >&3
else
	echo "Error: You did not specify the chain in which established connection should be hooked in" >&2
fi

