#!/bin/bash -e
#
# Flush all chains in the given table, remove all non-build-in chains
# and zero all counters in the build-in chains.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Tue, 13 Feb 2007 19:16:17 +0100
#

# Load the plugin routines
. /usr/share/alff/lib/plugin-routines

##
# Get the table name
table=`getOption ${1}`

if [ -z "${table}" ]; then
	echo "`basename $0`: Error: No table name specified..." >&2
	echo " Either create a symlink with the name clear_table_tableName" >&2
	echo " to this file or specify the tableName as command line parameter." >&2
	exit 1
fi

if ! isValidTable "${table}"; then
	echo "`basename $0`: Error: Invalid table \"${table}\"" >&2
	exit 1
fi

cat << EOF >&3
iptables -t ${table} -F
iptables -t ${table} -X
iptables -t ${table} -Z

EOF

##
# ip6tables kann kein nat
if [ ${table} != "nat" ] ; then
	cat << EOF >&3
ip6tables -t ${table} -F
ip6tables -t ${table} -X
ip6tables -t ${table} -Z

EOF
fi
