#!/bin/bash -e
#
# 01drop_spoofed
#
# Drop spoofed connection attemps
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Wed, 12 Apr 2006 19:00:04 +0200
#

. /usr/share/alff/lib/plugin-routines

##
# Make sure we have (an empty) chain
createChain spoofcheck

cat << EOF >&3
##
# RFC1918 networks
#
iptables -A spoofcheck -p all -i ! lo -s 10.0.0.0/8 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 10.0.0.0/8 -j DROP
#
iptables -A spoofcheck -p all -i ! lo -s 172.16.0.0/12 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 172.16.0.0/12 -j DROP
#
iptables -A spoofcheck -p all -i ! lo -s 192.168.0.0/16 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 192.168.0.0/16 -j DROP

##
# RFC 3330 networks
#
# documentation network
iptables -A spoofcheck -p all -i ! lo -s 192.0.2.0/24 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 192.0.2.0/24 -j DROP
# link local
iptables -A spoofcheck -p all -i ! lo -s 169.254.0.0/16 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 169.254.0.0/16 -j DROP

##
# Loopback address on eth* is probably not right
iptables -A spoofcheck -p all -i ! lo -s 127.0.0.0/8 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 127.0.0.0/8 -j DROP

EOF

# do the same for ipv6
cat << EOF >&3
##
# Some sample networks to block, there might be more

##
# site local unicast is deprecated (RFC3879)
ip6tables -A spoofcheck -p all -i ! lo -s fec0::/10 -j LOG --log-prefix "alff spoofed: "
ip6tables -A spoofcheck -p all -i ! lo -s fec0::/10 -j DROP

##
# Uniqe local unicast (RFC4193) should be opt in
ip6tables -A spoofcheck -p all -i ! lo -s fc00::/7 -j LOG --log-prefix "alff spoofed: "
ip6tables -A spoofcheck -p all -i ! lo -s fc00::/7 -j DROP

##
# Some more deprecated networks

##
# ipv4 compability, deprecated by RFC4291
ip6tables -A spoofcheck -p all -i ! lo -s ::/96 -j LOG --log-prefix "alff spoofed: "
ip6tables -A spoofcheck -p all -i ! lo -s ::/96 -j DROP

EOF
