#!/usr/bin/env sh
#
# 01drop_spoofed
#
# Drop spoofed connection attemps
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Wed, 12 Apr 2006 19:00:04 +0200
#
set -e

. /usr/share/alff/lib/plugin-routines

##
# Make sure we have (an empty) chain
createChain spoofcheck

cat << EOF >&3
##
# RFC1918 networks
#
iptables -A spoofcheck -p all -i ! lo -s 10.0.0.0/8 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 10.0.0.0/8 -j DROP
#
iptables -A spoofcheck -p all -i ! lo -s 172.16.0.0/12 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 172.16.0.0/12 -j DROP
#
iptables -A spoofcheck -p all -i ! lo -s 192.168.0.0/16 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 192.168.0.0/16 -j DROP

##
# RFC 3330 networks
#
# documentation network
iptables -A spoofcheck -p all -i ! lo -s 192.0.2.0/24 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 192.0.2.0/24 -j DROP
# link local
iptables -A spoofcheck -p all -i ! lo -s 169.254.0.0/16 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 169.254.0.0/16 -j DROP

##
# Loopback address on eth* is probably not right
iptables -A spoofcheck -p all -i ! lo -s 127.0.0.0/8 -j LOG --log-prefix "alff spoofed: "
iptables -A spoofcheck -p all -i ! lo -s 127.0.0.0/8 -j DROP

EOF
