#!/bin/sh -e
#
# create_chain_${chain}
#
# This plugin is just a wrapper to the createChain method of the alff library
# to be able to create a chain by just using this plugin.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Tue, 08 Aug 2006 16:45:04 +0200
#

# Load the plugin routines
. /usr/share/alff/lib/plugin-routines

if [ -z "${ALFF_CACHE_DIR_CHAINS}" ]; then
	echo "Error: You have to export ALFF_CACHE_DIR_CHAINS before running this script!" >&2
	exit 1
fi

if [ ! -d "${ALFF_CACHE_DIR_CHAINS}" ]; then
	echo "Error: ALFF_CACHE_DIR_CHAINS ${ALFF_CACHE_DIR_CHAINS} does not exist!" >&2
	exit 1
fi

##
# Get the chain name
chain=`basename $0 | cut -d_ -f3-`
if [ -z "${chain}" ]; then
	chain="$1"
fi

if [ -z "${chain}" ]; then
	echo "Error: No chain name specified..." >&2
	echo " Either create a symlink with the name create_chain_YourChainName" >&2
	echo " to this file or specify the YourChainName as command line parameter." >&2
	exit 1
fi

# Just call the createChain function
createChain ${chain}
