#!/bin/bash -e
#
# create_chain_log_and_reject
#
# Create (or recreate) a chain which logs a packet and drops it.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Mon, 24 Apr 2006 19:34:30 +0200
#

. /usr/share/alff/lib/plugin-routines

##
# Make sure we have (an empty) chain log_and_reject
createChain log_and_reject

cat << EOF >&3
# LOG the traffic to be rejected, but restrict the amount of logs...
iptables -A log_and_reject -m limit --limit 3/sec --limit-burst 5 -j LOG --log-prefix "alff rejected: "

# REJECT tcp connections gently by sending a tcp-reset
iptables -A log_and_reject -p tcp -j REJECT --reject-with tcp-reset

# REJECT anything else via an ICMP message with icmp-admin-prohibited
iptables -A log_and_reject -j REJECT --reject-with icmp-admin-prohibited

EOF
