#!/usr/bin/env sh
#
# 40drop_spoofed_packets_FORWARD
#
# Drop every packet which is surely spoofed.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Mon, 24 Apr 2006 19:57:56 +0200
#

# Nice litte trick to make this script more flexible
# The chain in which the spoofcheck chain should be hooked in has to be
# specified by providing _$CHAIN at the end of the symlink name to this
# script.
# (Thanks to the munin if_ plugin coders for this idea)
CHAIN=`basename $0 | awk -F_ '{ print $NF }'`

if [ "${CHAIN}" ]; then

	if [ -f "${CACHE_DIR_CHAINS}/filter/spoofcheck"  ]; then
		echo " * Creating rule to DROP spoofed packets... "
		echo "iptables -A ${CHAIN} -j spoofcheck" >&3
	else
		echo "Error: Chain \"spoofcheck\" does not exist, but should be hooked in into ${CHAIN}!">&2
	fi
else
	echo "Error: You did not specify the chain in which 'spoofcheck' should be hooked in" >&2
fi
