#!/bin/sh -e
#
# drop_spoofed_packets_
#
# Drop every packet which is surely spoofed.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Mon, 24 Apr 2006 19:57:56 +0200
#

. /usr/share/alff/lib/plugin-routines

chain=`getOption "$1"`

if [ "${chain}" ]; then

	vaild_chain='false'
	case "${chain}" in
		INPUT|FORWARD)
			valid_chain='true'
			;;
		*)
			if chainExists "${1}" "filter"; then
				valid_chain='true'
			fi
	esac

	if [ "${valid_chain}" = 'true' ]; then
		echo " * Creating rule to DROP spoofed packets... "
		echo "iptables -A ${chain} -j spoofcheck" >&3
	else
		echo "Error: Chain \"spoofcheck\" does not exist, but should be hooked in into ${chain}!">&2
	fi
else
	echo "Error: You did not specify the chain in which 'spoofcheck' should be hooked in" >&2
fi
