#!/usr/bin/perl -w
#
# enable_DHCP_relay_FORWARD
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 20:26:52 +0200
#

use strict;
use Alff::Main;
use Alff::Config;

# Read configuration from the config file (correct config space is passed via env.)
my $config = Alff::Config->new();
my $alff = Alff::Main->new();

my $chain = "allowDHCP";

my @dhcp_servers = $config->getDHCPServers;

if ( scalar( @dhcp_servers ) == 0 ) {
	print " * No DHCP servers configured in alff.conf. Staying cool.\n";
	exit 0;
}

print " * Allowing DHCP traffic to configured DHCP servers... ";
$alff->create_chain( $chain );

$alff->write_line("iptables -A FORWARD -p udp --sport 67:68 --dport 67:68 -j $chain");
$alff->write_line("ip6tables -A FORWARD -p udp --sport 546:547 --dport 546:547 -j $chain");

foreach my $dhcp_server ( @dhcp_servers ) {
	if($alff->getIpVersion($dhcp_server) == 4) {
		$alff->write_line("iptables -A $chain -d $dhcp_server -p udp --sport 68 --dport 67 -j ACCEPT");
		$alff->write_line("iptables -A $chain -s $dhcp_server -p udp --sport 67 --dport 68 -j ACCEPT");
		# This is neccessary if your firewall isn´t a dhcprelay itself
		$alff->write_line("iptables -A $chain -s $dhcp_server -p udp --sport 67 --dport 67 -j ACCEPT");
	} elsif ($alff->getIpVersion($dhcp_server) == 6) {
		$alff->write_line("ip6tables -A $chain -d $dhcp_server -p udp --sport 546 --dport 547 -j ACCEPT");
		$alff->write_line("ip6tables -A $chain -s $dhcp_server -p udp --sport 547 --dport 546 -j ACCEPT");
		# This is neccessary if your firewall isn´t a dhcprelay itself
		$alff->write_line("ip6tables -A $chain -s $dhcp_server -p udp --sport 547 --dport 547 -j ACCEPT");
	} else {
		print "ERROR: can't determine ip version of dhcp server $dhcp_server\n";
	}
		
}
print "done.\n";
