#!/usr/bin/perl -w
#
# enable_DHCP_relay_INPUT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 19:56:00 +0200
#

use strict;
use Alff::Main;
use Alff::Config;

# Read configuration from the config file (correct config space is passed via env.)
my $config = Alff::Config->new;
my $alff = Alff::Main->new;

my @dhcp_servers = $config->getDHCPServers;

if ( scalar( @dhcp_servers ) > 0 ) {

	print " * Allowing DHCP traffic to local DHCP relay... ";
	$alff->write_line("iptables -A INPUT -p udp -d 255.255.255.255 --sport 68 --dport 67 -j ACCEPT");

	foreach my $dhcp_server ( @dhcp_servers ) {
		$alff->write_line("iptables  -A INPUT -p udp -s $dhcp_server --sport 67 -j ACCEPT");
	}
	print "done.\n";
}
