#!/usr/bin/perl -w
#
# enable_DHCP_relay_INPUT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 19:56:00 +0200
#

use strict;
use Alff::Main;
use Alff::Config;

# Read configuration from the config file (correct config space is passed via env.)
my $config = Alff::Config->new;
my $alff = Alff::Main->new;

my @dhcp_servers = $config->getDHCPServers;

if ( scalar( @dhcp_servers ) == 0 ) {
	print STDERR " * No DHCP servers in alff.conf. Staying cool.\n";
	exit 0;
}

print " * Allowing DHCP traffic to local DHCP relay... ";
$alff->write_line("iptables -A INPUT -p udp -d 255.255.255.255 --sport 68 --dport 67 -j ACCEPT");
$alff->write_line("ip6tables -A INPUT -p udp -d ff02::1:2 --sport 546 --dport 547 -j ACCEPT");

foreach my $dhcp_server ( @dhcp_servers ) {
	if ($alff->getIpVersion($dhcp_server) == 4) {
		$alff->write_line("iptables  -A INPUT -p udp -s $dhcp_server --sport 67 -j ACCEPT");
	} elsif ($alff->getIpVersion($dhcp_server) == 6) {
		$alff->write_line("ip6tables  -A INPUT -p udp -s $dhcp_server --sport 547 -j ACCEPT");
	} else {
		print "ERROR: can't determine ip version of dhcp server $dhcp_server\n";
	}
}
print "done.\n";
