#!/bin/bash -e
#
# finish_FORWARD
#
# Gracefully close the FORWARD chain.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Mon, 24 Apr 2006 20:22:38 +0200
#

cat << EOF >&3
iptables -A FORWARD -m limit --limit 5/sec -j LOG --limit-burst 10 --log-prefix "alff rejected: "
iptables -A FORWARD -p tcp -j REJECT --reject-with tcp-reset
iptables -A FORWARD -j REJECT --reject-with icmp-admin-prohibited

ip6tables -A FORWARD -m limit --limit 5/sec -j LOG --limit-burst 10 --log-prefix "alff rejected: "
ip6tables -A FORWARD -p tcp -j REJECT --reject-with tcp-reset
ip6tables -A FORWARD -j REJECT --reject-with icmp6-adm-prohibited

EOF
