#!/usr/bin/perl -w
#
# generateServiceChains
#
# Generate an iptables chain an host/port rules for each configured
# service. (as in run the service-setup-tool for every service)
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 02 Jun 2006 00:18:40 +0200
#

use strict;
use Alff::Config;
use Alff::Main;
use Alff::Service;

my $debug = 0;
my $services_d = "/etc/alff/services.d/";

if ( ! -d $services_d ) {
	print STDERR "Error: services.d directory $services_d does not exist.";
	exit 1;
}

my $alff_config = Alff::Config->new();
my $alff_main = Alff::Main->new();
my $alff_srv = Alff::Service->new( alff_main => $alff_main, services_d => $services_d, debug => $debug );

my @securityClasses = $alff_config->getSecurityClasses();
my @services = $alff_srv->readServiceNames();

if ( $debug ) {
	print STDERR "INFO: Found securityClasses: " . join( ', ', @securityClasses ) . "\n";
	print STDERR "INFO: Found services: " . join( ', ', @services ) . "\n";
}

print " * Creating security class chains...\n";
foreach my $secClass ( @securityClasses ) {
	my $chain = "allowServicesFrom" . ucfirst( ${secClass} ) . "Nets";
	print "  - $chain\n" if ( $debug );
	$alff_main->create_chain( $chain );
}
$alff_main->create_chain( "allowWorldOpenServices" );

print " * Creating service rules...\n";
foreach my $srv ( @services ) {
	print "   - $srv\n";
	$alff_srv->generateServiceChain( $srv );
}
