#!/usr/bin/perl -w
#
# handleUdpTraceroute
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Sun, 16 Jul 2006 19:49:21 +0200
#

use strict;
use Alff::Config;
use Alff::Main;

my $config = Alff::Config->new();
my $alff = Alff::Main->new;

my $allow_traceroute_udp = $config->getOption( "allow_traceroute_udp" );

if ( $allow_traceroute_udp eq "yes" ) {
	print " * Allowing udp traceroute...\n";
	$alff->write_line("iptables -A FORWARD -p udp --dport 33434:33523 -j ACCEPT");
	$alff->write_line("ip6tables -A FORWARD -p udp --dport 33434:33523 -j ACCEPT");
}
