#!/usr/bin/perl -w
#
# hookInServiceChains
#
# Hook the chains for services now
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 28 Apr 2006 15:20:59 +0200
#

use strict;
use Alff::Config;
use Alff::Service;

my $config = Alff::Config->new();
my $services = Alff::Service->new;

$services->allowWorldOpenServices;

my @securityClasses = $config->getSecurityClasses();
foreach my $secClass ( @securityClasses ) {
	$services->allowServiceFromNetworksOfSecurityClass( $secClass );
}

