#!/bin/bash -e
#
# hookInBlackAndWhitelist
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Mon, 17 Jul 2006 16:24:50 +0200
#

. /usr/share/alff/lib/plugin-routines

CHAINS="blacklist whitelist"

echo -n " * Creating "
for chain in ${CHAINS}; do
	echo -n "${chain} "
	if ! chainExists ${chain}; then
		createChain ${chain}
	fi

	echo "iptables -A FORWARD -j ${chain}" >&3
	echo "ip6tables -A FORWARD -j ${chain}" >&3
done

echo " done."
