#!/bin/bash
#
# print_info
#
# Print little information about the status of processing
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Thu, 27 Apr 2006 20:42:39 +0200
#

. /usr/share/alff/lib/plugin-routines

# Nice litte trick to make this script more flexible
# The chain in which the spoofcheck chain should be hooked in has to be
# specified by providing _$CHAIN at the end of the symlink name to this
# script.
# (Thanks to the munin if_ plugin coders for this idea)
CHAIN=`getOption "$1"`

cat << EOMSG

Setting up the ${CHAIN} chain...
EOMSG
