#!/bin/bash
#
# update-git
#
# Pull configuration from GIT before building rules
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Wed, 21 Jun 2006 13:39:56 +0200
#
#
# Mark this script as executable to use it.
#
set -e

CONFIG_DIR="/etc/alff"

	pushd "${CONFIG_DIR}" >/dev/null
	echo -n " * Updating local config repository... "
	if git pull >/dev/null; then
		echo "done".

		echo -n " * Pushing local changes to server... "
		if git push >/dev/null; then
			exit 0
		fi
	fi

	echo "There went something wrong!"
	exit 1
