#!/usr/bin/env sh
#
# Helper routines to be used in shell based plugins
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Mon, 17 Jul 2006 16:18:04 +0200
#

if [ -z "${ALFF_CACHE_DIR_CHAINS}" ]; then
	echo "Error: $0 seems not to be run by alff." >&2
	echo "If you think you know what you're doing you might want to" >&2
	echo "  export ALFF_CACHE_DIR_CHAINS=\"/var/cache/alff/<config_space>/chains/\"" >&2
	echo "or whereever your placed it." >&2
	exit 1
fi
	
if [ ! -d "${ALFF_CACHE_DIR_CHAINS}" ]; then
	echo "Error: ALFF_CACHE_DIR_CHAINS ${ALFF_CACHE_DIR_CHAINS} does not exist!" >&2
	exit 1
fi

# Check if the given chain exists.
# If no table is specified, 'filter' is assumed.
# Usage: chainExists chain [ table ]
function chainExists() { #{{{
	local table="${2:-filter}"
	local chain="$1"

	if [ -f "${ALFF_CACHE_DIR_CHAINS}/${table}/${chain}" ]; then
		return 0
	else	
		return 1
	fi
} #}}}

# Create the given chain in the given table if it does not exist.
# If no table is specified, 'filter# is assumed.

function createChain() { #{{{
	# Get the chain name.
	local chain="$1"
	# If we got a table, use it, default to 'filter' else.
	local table=${2:-filter}

	if [ -z "${chain}" ]; then
		echo "Error: No chain name specified..." >&2
		echo " Either create a symlink with the name create_chain_YourChainName" >&2
		echo " to this file or specify the YourChainName as command line parameter." >&2
		exit 1
	fi
	
	if [ ! -f "${ALFF_CACHE_DIR_CHAINS}/${table}/${chain}" ]; then
		touch "${ALFF_CACHE_DIR_CHAINS}/${table}/${chain}"

		##
		# If not already there, create ${chain}
cat << EOF >&3

if ! iptables -t ${table} -F ${chain} >/dev/null 2>&1; then
	iptables -t ${table} -N ${chain}
fi
EOF
	fi
} #}}}

# This function will 'echo' back the plugin was called with.
# It first checks if $0 contains any value after the last '_' and if not
# checks for "$1".
#
# (Thanks to the munin if_ plugin coders for this idea!)
#
# Usagge: getOption $1
function getOption() { # {{{ 
	local chain=`basename $0 | awk -F_ '{ print $NF }'`

	if [ ! "${chain}" ]; then
		chain="${1}"
	fi

	echo "${chain}"
}
# }}}

# vim:foldmethod=marker
