#!/usr/bin/env sh
#
# alff routines
#
# Maximilian Wilhelm <max@rfc2324.org>
#  -- Fri, 28 Apr 2006 19:52:22 +0200
#



##
function configureFirewallNetworkOptions() { # {{{

	# Get fw_type configuration option
	FW_TYPE=`alff getOption -nocheck fw_type`

	echo  " * Configuring networking feature for ${FW_TYPE} mode..."

	case "${FW_TYPE}" in 
		bridge)
			# If we are running as a bridge, 
			#- enable hooks only for used filter features
			cat << EOCONF >&3
echo 0 > /proc/sys/net/bridge/bridge-nf-call-arptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
echo 0 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
echo 1 > /proc/sys/net/bridge/bridge-nf-filter-vlan-tagged
EOCONF

			echo "" >&2
			echo "" >&2
			echo "WARNING: You are using bridging mode firewall..." >&2
			echo "This part of alff is not tested very well anymore!" >&2
			echo ""
			sleep 3
			;;

		router)
			cat << EOCONF >&3
echo 1 > /proc/sys/net/ipv4/ip_forward

EOCONF
			;;

	esac
}
# }}}

# vim:foldmethod=marker
